// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package wordle

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Guess           protoreflect.MessageDescriptor
	fd_Guess_index     protoreflect.FieldDescriptor
	fd_Guess_word      protoreflect.FieldDescriptor
	fd_Guess_submitter protoreflect.FieldDescriptor
	fd_Guess_count     protoreflect.FieldDescriptor
)

func init() {
	file_wordle_wordle_guess_proto_init()
	md_Guess = File_wordle_wordle_guess_proto.Messages().ByName("Guess")
	fd_Guess_index = md_Guess.Fields().ByName("index")
	fd_Guess_word = md_Guess.Fields().ByName("word")
	fd_Guess_submitter = md_Guess.Fields().ByName("submitter")
	fd_Guess_count = md_Guess.Fields().ByName("count")
}

var _ protoreflect.Message = (*fastReflection_Guess)(nil)

type fastReflection_Guess Guess

func (x *Guess) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Guess)(x)
}

func (x *Guess) slowProtoReflect() protoreflect.Message {
	mi := &file_wordle_wordle_guess_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Guess_messageType fastReflection_Guess_messageType
var _ protoreflect.MessageType = fastReflection_Guess_messageType{}

type fastReflection_Guess_messageType struct{}

func (x fastReflection_Guess_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Guess)(nil)
}
func (x fastReflection_Guess_messageType) New() protoreflect.Message {
	return new(fastReflection_Guess)
}
func (x fastReflection_Guess_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Guess
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Guess) Descriptor() protoreflect.MessageDescriptor {
	return md_Guess
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Guess) Type() protoreflect.MessageType {
	return _fastReflection_Guess_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Guess) New() protoreflect.Message {
	return new(fastReflection_Guess)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Guess) Interface() protoreflect.ProtoMessage {
	return (*Guess)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Guess) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_Guess_index, value) {
			return
		}
	}
	if x.Word != "" {
		value := protoreflect.ValueOfString(x.Word)
		if !f(fd_Guess_word, value) {
			return
		}
	}
	if x.Submitter != "" {
		value := protoreflect.ValueOfString(x.Submitter)
		if !f(fd_Guess_submitter, value) {
			return
		}
	}
	if x.Count != "" {
		value := protoreflect.ValueOfString(x.Count)
		if !f(fd_Guess_count, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Guess) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "wordle.wordle.Guess.index":
		return x.Index != ""
	case "wordle.wordle.Guess.word":
		return x.Word != ""
	case "wordle.wordle.Guess.submitter":
		return x.Submitter != ""
	case "wordle.wordle.Guess.count":
		return x.Count != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: wordle.wordle.Guess"))
		}
		panic(fmt.Errorf("message wordle.wordle.Guess does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Guess) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "wordle.wordle.Guess.index":
		x.Index = ""
	case "wordle.wordle.Guess.word":
		x.Word = ""
	case "wordle.wordle.Guess.submitter":
		x.Submitter = ""
	case "wordle.wordle.Guess.count":
		x.Count = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: wordle.wordle.Guess"))
		}
		panic(fmt.Errorf("message wordle.wordle.Guess does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Guess) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "wordle.wordle.Guess.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "wordle.wordle.Guess.word":
		value := x.Word
		return protoreflect.ValueOfString(value)
	case "wordle.wordle.Guess.submitter":
		value := x.Submitter
		return protoreflect.ValueOfString(value)
	case "wordle.wordle.Guess.count":
		value := x.Count
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: wordle.wordle.Guess"))
		}
		panic(fmt.Errorf("message wordle.wordle.Guess does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Guess) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "wordle.wordle.Guess.index":
		x.Index = value.Interface().(string)
	case "wordle.wordle.Guess.word":
		x.Word = value.Interface().(string)
	case "wordle.wordle.Guess.submitter":
		x.Submitter = value.Interface().(string)
	case "wordle.wordle.Guess.count":
		x.Count = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: wordle.wordle.Guess"))
		}
		panic(fmt.Errorf("message wordle.wordle.Guess does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Guess) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "wordle.wordle.Guess.index":
		panic(fmt.Errorf("field index of message wordle.wordle.Guess is not mutable"))
	case "wordle.wordle.Guess.word":
		panic(fmt.Errorf("field word of message wordle.wordle.Guess is not mutable"))
	case "wordle.wordle.Guess.submitter":
		panic(fmt.Errorf("field submitter of message wordle.wordle.Guess is not mutable"))
	case "wordle.wordle.Guess.count":
		panic(fmt.Errorf("field count of message wordle.wordle.Guess is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: wordle.wordle.Guess"))
		}
		panic(fmt.Errorf("message wordle.wordle.Guess does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Guess) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "wordle.wordle.Guess.index":
		return protoreflect.ValueOfString("")
	case "wordle.wordle.Guess.word":
		return protoreflect.ValueOfString("")
	case "wordle.wordle.Guess.submitter":
		return protoreflect.ValueOfString("")
	case "wordle.wordle.Guess.count":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: wordle.wordle.Guess"))
		}
		panic(fmt.Errorf("message wordle.wordle.Guess does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Guess) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in wordle.wordle.Guess", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Guess) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Guess) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Guess) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Guess) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Guess)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Word)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Submitter)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Count)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Guess)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Count) > 0 {
			i -= len(x.Count)
			copy(dAtA[i:], x.Count)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Count)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Submitter) > 0 {
			i -= len(x.Submitter)
			copy(dAtA[i:], x.Submitter)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Submitter)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Word) > 0 {
			i -= len(x.Word)
			copy(dAtA[i:], x.Word)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Word)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Guess)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Guess: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Guess: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Word", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Word = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Submitter = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Count = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: wordle/wordle/guess.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Guess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Word      string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Submitter string `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Count     string `protobuf:"bytes,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Guess) Reset() {
	*x = Guess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordle_wordle_guess_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guess) ProtoMessage() {}

// Deprecated: Use Guess.ProtoReflect.Descriptor instead.
func (*Guess) Descriptor() ([]byte, []int) {
	return file_wordle_wordle_guess_proto_rawDescGZIP(), []int{0}
}

func (x *Guess) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Guess) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Guess) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *Guess) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

var File_wordle_wordle_guess_proto protoreflect.FileDescriptor

var file_wordle_wordle_guess_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x2f,
	0x67, 0x75, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x77, 0x6f, 0x72,
	0x64, 0x6c, 0x65, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x22, 0x65, 0x0a, 0x05, 0x47, 0x75,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x42, 0x8e, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65,
	0x2e, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x42, 0x0a, 0x47, 0x75, 0x65, 0x73, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x18, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0xa2,
	0x02, 0x03, 0x57, 0x57, 0x58, 0xaa, 0x02, 0x0d, 0x57, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x2e, 0x57,
	0x6f, 0x72, 0x64, 0x6c, 0x65, 0xca, 0x02, 0x0d, 0x57, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x5c, 0x57,
	0x6f, 0x72, 0x64, 0x6c, 0x65, 0xe2, 0x02, 0x19, 0x57, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x5c, 0x57,
	0x6f, 0x72, 0x64, 0x6c, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0e, 0x57, 0x6f, 0x72, 0x64, 0x6c, 0x65, 0x3a, 0x3a, 0x57, 0x6f, 0x72, 0x64,
	0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wordle_wordle_guess_proto_rawDescOnce sync.Once
	file_wordle_wordle_guess_proto_rawDescData = file_wordle_wordle_guess_proto_rawDesc
)

func file_wordle_wordle_guess_proto_rawDescGZIP() []byte {
	file_wordle_wordle_guess_proto_rawDescOnce.Do(func() {
		file_wordle_wordle_guess_proto_rawDescData = protoimpl.X.CompressGZIP(file_wordle_wordle_guess_proto_rawDescData)
	})
	return file_wordle_wordle_guess_proto_rawDescData
}

var file_wordle_wordle_guess_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wordle_wordle_guess_proto_goTypes = []interface{}{
	(*Guess)(nil), // 0: wordle.wordle.Guess
}
var file_wordle_wordle_guess_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wordle_wordle_guess_proto_init() }
func file_wordle_wordle_guess_proto_init() {
	if File_wordle_wordle_guess_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wordle_wordle_guess_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wordle_wordle_guess_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wordle_wordle_guess_proto_goTypes,
		DependencyIndexes: file_wordle_wordle_guess_proto_depIdxs,
		MessageInfos:      file_wordle_wordle_guess_proto_msgTypes,
	}.Build()
	File_wordle_wordle_guess_proto = out.File
	file_wordle_wordle_guess_proto_rawDesc = nil
	file_wordle_wordle_guess_proto_goTypes = nil
	file_wordle_wordle_guess_proto_depIdxs = nil
}
